### ISSUE TITLE
GISAID & Scraping 

### ISSUE THREAD

**Issue by greysonlalonde** [poeli/EpiCoV_downloader#13]
Please note this comment: [https://github.com/nextstrain/ncov/issues/53#issuecomment-612454452](url)

**Comment by poeli-lanl** [comment]
I believe my code was no longer able to scrap gisaid record since the direct links were provided, but I will double check. Thanks for the reminder.

**Comment by greysonlalonde** [comment]
Sounds good, thanks! [https://github.com/greysonlalonde/gisaid-uploader ](url) will have a download capability and be functioning within the next month if you still have the need.
