### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by philiptzou** [poeli/EpiCoV_downloader#2]
Hello,

First of all, I want to thank you for creating this great downloader script - we have exactly same problem downloading the nextstrain fasta sequences from EPICoV and this script solved it.

To integrate the script with our system, I created a Dockerfile to make it runs from inside a Docker container. I hope this will make it easier to use - only need to install Docker as dependency. The forked version is located here:

https://github.com/philiptzou/EpiCoV_downloader

I also published our pre-build docker image on Docker hub at [hivdb/epicov-downloader](https://hub.docker.com/r/hivdb/epicov-downloader). A user just need to add the three environment variables to `epicov-downloader.sh` then she/he can run it without any overhead.

I am not seeking for merging back at current stage since the Docker container currently only supports downloading nextstrain fasta/tsv files. However, I hope it can help you and others to use this script with Docker and probably adding Docker support eventually.

**Comment by poeli-lanl** [comment]
Hello, I apologize for missing your message. It's really a good idea for dockerizing the app. Thanks for building the docker file!
